---
- name: Déploiement d'Apache sur mes serveurs EC2
  hosts: web
  become: true

  vars:
    apache_package: apache2
    apache_service: apache2

  tasks:
    - name: Mettre à jour la liste des paquets
      apt:
        update_cache: yes

    - name: Installer Apache
      apt:
        name: "{{ apache_package }}"
        state: present

    - name: S'assurer qu'Apache est démarré et activé au démarrage
      service:
        name: "{{ apache_service }}"
        state: started
        enabled: true

    - name: Copier la page d'accueil personnalisée
      copy:
        src: index.html
        dest: /var/www/html/index.html
        owner: www-data
        group: www-data
        mode: '0644'
      notify: Redémarrer Apache

  handlers:
    - name: Redémarrer Apache
      service:
        name: "{{ apache_service }}"
        state: restarted

